"""Locked metric dictionary for Plan 10 rollout/cleanup gates.

Definitions only — no live collectors. Numerator/denominator/eligibility/window
and confidence model are frozen for Task 1+ dry-runs and rollout revisions.
"""

from __future__ import annotations

from app.assistant.migration.contracts import MetricDefinition

METRIC_DICTIONARY: tuple[MetricDefinition, ...] = (
    MetricDefinition(
        metric_id="task_completion_rate",
        display_name="Task completion rate",
        numerator="eligible runs with terminal success status",
        denominator="eligible comparable runs in window",
        eligibility="production chat runs under active rollout revision; exclude cancelled-by-user and admission-fallback",
        window="rollout_revision_metric_window",
        confidence_model="wilson",
        gate_threshold="main_agent >= legacy - 0.02",
        stage_applicability=("shadow", "read", "write", "cleanup"),
    ),
    MetricDefinition(
        metric_id="user_visible_failure_rate",
        display_name="User-visible failure rate",
        numerator="eligible runs with user-visible failure/error terminal",
        denominator="eligible comparable runs in window",
        eligibility="production chat runs; exclude staff diagnostics",
        window="rollout_revision_metric_window",
        confidence_model="wilson",
        gate_threshold="main_agent - legacy <= 0.01",
        stage_applicability=("read", "write", "cleanup"),
    ),
    MetricDefinition(
        metric_id="p95_e2e_latency_ratio",
        display_name="p95 end-to-end latency ratio",
        numerator="main_agent p95 latency_ms",
        denominator="legacy p95 latency_ms on comparable cohort",
        eligibility="eligible paired/comparable runs only",
        window="rollout_revision_metric_window",
        confidence_model="bootstrap",
        gate_threshold="<= 1.5x legacy",
        stage_applicability=("read", "write", "cleanup"),
    ),
    MetricDefinition(
        metric_id="mean_normalized_token_ratio",
        display_name="Mean normalized model token ratio",
        numerator="main_agent mean normalized tokens",
        denominator="legacy mean normalized tokens",
        eligibility="eligible comparable runs with token accounting",
        window="rollout_revision_metric_window",
        confidence_model="bootstrap",
        gate_threshold="<= 1.35x legacy unless approved non-safety exception",
        stage_applicability=("read", "write", "cleanup"),
    ),
    MetricDefinition(
        metric_id="unauthorized_capability_calls",
        display_name="Unauthorized capability calls",
        numerator="capability calls denied post-dispatch or policy-violating",
        denominator="1 (exact count gate)",
        eligibility="all production capability calls under active revision",
        window="rollout_revision_metric_window",
        confidence_model="exact_zero",
        gate_threshold="== 0",
        stage_applicability=("shadow", "read", "write", "cleanup"),
    ),
    MetricDefinition(
        metric_id="real_shadow_writes",
        display_name="Real shadow writes",
        numerator="shadow/eval path writes that mutated production state",
        denominator="1 (exact count gate)",
        eligibility="all runtime_shadow eval runs and shadow comparisons",
        window="rollout_revision_metric_window",
        confidence_model="exact_zero",
        gate_threshold="== 0",
        stage_applicability=("shadow", "read", "write", "cleanup"),
    ),
    MetricDefinition(
        metric_id="eval_shadow_visibility_leaks",
        display_name="Eval shadow visibility/privacy leaks",
        numerator="normal API surfaces that accepted eval run IDs or leaked shadow content",
        denominator="1 (exact count gate)",
        eligibility="production history/active/SSE/artifact/search APIs",
        window="rollout_revision_metric_window",
        confidence_model="exact_zero",
        gate_threshold="== 0",
        stage_applicability=("shadow", "read", "write", "cleanup"),
    ),
    MetricDefinition(
        metric_id="duplicate_local_or_external_writes",
        display_name="Duplicate local/external writes",
        numerator="duplicate side-effect settlements for same idempotency key",
        denominator="1 (exact count gate)",
        eligibility="ledger-enforced write calls",
        window="rollout_revision_metric_window",
        confidence_model="exact_zero",
        gate_threshold="== 0",
        stage_applicability=("write", "cleanup"),
    ),
    MetricDefinition(
        metric_id="false_completion_with_obligations",
        display_name="False completion with open obligations",
        numerator="runs marked complete while obligations remain open",
        denominator="1 (exact count gate)",
        eligibility="main agent runs with obligation ledger",
        window="rollout_revision_metric_window",
        confidence_model="exact_zero",
        gate_threshold="== 0",
        stage_applicability=("read", "write", "cleanup"),
    ),
    MetricDefinition(
        metric_id="unresolved_reconciliation_calls",
        display_name="Unresolved reconciliation calls",
        numerator="calls in unknown/needs_reconciliation at gate time",
        denominator="1 (exact count gate)",
        eligibility="all capability calls for eligible runs",
        window="cleanup_gate_snapshot",
        confidence_model="exact_zero",
        gate_threshold="== 0",
        stage_applicability=("write", "cleanup"),
    ),
    MetricDefinition(
        metric_id="injection_accuracy",
        display_name="Skill injection / direct-answer accuracy",
        numerator="cases with correct injection or direct-answer decision",
        denominator="fixed offline + stratified online sample",
        eligibility="gate-eligible eval datasets + manual sample",
        window="dataset_version + sample_window",
        confidence_model="wilson",
        gate_threshold="direct-answer/no-skill >= 0.90; false injection <= 0.05",
        stage_applicability=("shadow", "read", "write"),
    ),
    MetricDefinition(
        metric_id="acceptable_capability_path",
        display_name="Acceptable capability path rate",
        numerator="cases with acceptable capability path",
        denominator="comparable evaluated cases",
        eligibility="fixed offline datasets + shadow comparisons",
        window="dataset_version + sample_window",
        confidence_model="wilson",
        gate_threshold=">= 0.85",
        stage_applicability=("shadow", "read", "write"),
    ),
    MetricDefinition(
        metric_id="recovery_success_rate",
        display_name="Worker recovery / resume success",
        numerator="recoveries/resumes that restore nonterminal run correctly",
        denominator="recovery/resume attempts in window",
        eligibility="durable main agent runs with lease recovery or HITL resume",
        window="rollout_revision_metric_window",
        confidence_model="wilson",
        gate_threshold="within tested invariants (no silent drop)",
        stage_applicability=("read", "write", "cleanup"),
    ),
    MetricDefinition(
        metric_id="sse_replay_integrity",
        display_name="SSE replay integrity",
        numerator="replays matching durable event sequence digests",
        denominator="SSE replay requests in window",
        eligibility="durable runs with client reconnect",
        window="rollout_revision_metric_window",
        confidence_model="exact_zero",
        gate_threshold="mismatches == 0",
        stage_applicability=("read", "write", "cleanup"),
        notes="Reported as mismatch count; confidence_model exact_zero on mismatches",
    ),
    MetricDefinition(
        metric_id="legacy_access_count",
        display_name="Legacy runtime access count",
        numerator="legacy router/supervisor/table read-write/invocation observations",
        denominator="1 (exact count gate)",
        eligibility="production import/query/runtime telemetry after cutover",
        window="cleanup_zero_access_window",
        confidence_model="exact_zero",
        gate_threshold="== 0 for final 7 days before B1",
        stage_applicability=("cleanup",),
    ),
    MetricDefinition(
        metric_id="l2_namespace_blocker_count",
        display_name="L2 namespace blocker count",
        numerator="active L2 rows with null/invalid/split package-namespace identity",
        denominator="1 (exact count gate)",
        eligibility="all active L2 rows",
        window="cleanup_gate_snapshot",
        confidence_model="exact_zero",
        gate_threshold="== 0",
        stage_applicability=("write", "cleanup"),
    ),
)


def required_metric_ids() -> set[str]:
    """Metric IDs that Task 0 must define for later rollout/cleanup gates."""
    return {
        "task_completion_rate",
        "user_visible_failure_rate",
        "p95_e2e_latency_ratio",
        "mean_normalized_token_ratio",
        "unauthorized_capability_calls",
        "real_shadow_writes",
        "eval_shadow_visibility_leaks",
        "duplicate_local_or_external_writes",
        "false_completion_with_obligations",
        "unresolved_reconciliation_calls",
        "injection_accuracy",
        "acceptable_capability_path",
        "recovery_success_rate",
        "sse_replay_integrity",
        "legacy_access_count",
        "l2_namespace_blocker_count",
    }


__all__ = ("METRIC_DICTIONARY", "required_metric_ids")
