"""Plan 05 source-aware agent policy package (contracts + pure evaluators).

Task 1 freezes exposure/conflict/budget/effective-policy contracts.
Later tasks add evaluator, evidence, budget ledger, obligations, and runtime.
"""

from app.assistant.policy.conflicts import (
    SkillConflictError,
    SkillConflictEvaluationResult,
    SkillConflictIdentity,
    SkillConflictParticipant,
    build_catalog_name_index,
    conflicts_symmetric,
    evaluate_skill_conflicts,
    resolve_target_skill,
)
from app.assistant.policy.contracts import (
    ASSISTANT_CHAT_ENTRYPOINT_POLICY_DIGEST,
    ASSISTANT_CHAT_ENTRYPOINT_POLICY_REVISION,
    ASSISTANT_CHAT_RUN_BUDGET_DEFAULTS,
    ASSISTANT_CHAT_RUN_BUDGET_HARD_CEILINGS,
    CapabilityExposureRef,
    EffectiveRunPolicySnapshot,
    MAIN_AGENT_OWNER_DEFAULT_MAX_CALLS,
    ManifestExposureIndex,
    OwnerBudgetLimits,
    OwnerPolicyRef,
    PLAN05_RELEASE_GATE_SIDE_EFFECTS,
    RunBudgetLimits,
    build_capability_exposure_ref,
    build_effective_run_policy_snapshot,
    build_manifest_exposure_index,
    build_owner_budget_limits,
    build_owner_policy_ref,
    compute_assistant_chat_entrypoint_policy_digest,
    compute_default_global_policy_digest,
    compute_effective_policy_digest,
    compute_exposure_digest,
    compute_exposure_index_digest,
    compute_grant_source_set_digest,
    compute_owner_budget_digest,
    compute_owner_policy_digest,
    normalize_owner_budget_limits,
    normalize_run_budget_limits,
)
from app.assistant.policy.exposures import (
    DuplicateCapabilityDeclaration,
    ExistingExposureCompatibilityView,
    ExposureBindingInput,
    ExposureBuildError,
    ExposureOwnerIdentity,
    append_compatible_consumer,
    build_exposure_ref_from_input,
    build_manifest_exposure_index_from_inputs,
    choose_batch_owner,
    evaluate_duplicate_capability_compatibility,
    resolve_owner_from_binding,
)
from app.assistant.skills.contracts import SkillConflictRuleV1

__all__ = [
    "ASSISTANT_CHAT_ENTRYPOINT_POLICY_DIGEST",
    "ASSISTANT_CHAT_ENTRYPOINT_POLICY_REVISION",
    "ASSISTANT_CHAT_RUN_BUDGET_DEFAULTS",
    "ASSISTANT_CHAT_RUN_BUDGET_HARD_CEILINGS",
    "CapabilityExposureRef",
    "DuplicateCapabilityDeclaration",
    "EffectiveRunPolicySnapshot",
    "ExistingExposureCompatibilityView",
    "ExposureBindingInput",
    "ExposureBuildError",
    "ExposureOwnerIdentity",
    "MAIN_AGENT_OWNER_DEFAULT_MAX_CALLS",
    "ManifestExposureIndex",
    "OwnerBudgetLimits",
    "OwnerPolicyRef",
    "PLAN05_RELEASE_GATE_SIDE_EFFECTS",
    "RunBudgetLimits",
    "SkillConflictError",
    "SkillConflictEvaluationResult",
    "SkillConflictIdentity",
    "SkillConflictParticipant",
    "SkillConflictRuleV1",
    "append_compatible_consumer",
    "build_capability_exposure_ref",
    "build_catalog_name_index",
    "build_effective_run_policy_snapshot",
    "build_exposure_ref_from_input",
    "build_manifest_exposure_index",
    "build_manifest_exposure_index_from_inputs",
    "build_owner_budget_limits",
    "build_owner_policy_ref",
    "choose_batch_owner",
    "compute_assistant_chat_entrypoint_policy_digest",
    "compute_default_global_policy_digest",
    "compute_effective_policy_digest",
    "compute_exposure_digest",
    "compute_exposure_index_digest",
    "compute_grant_source_set_digest",
    "compute_owner_budget_digest",
    "compute_owner_policy_digest",
    "conflicts_symmetric",
    "evaluate_duplicate_capability_compatibility",
    "evaluate_skill_conflicts",
    "normalize_owner_budget_limits",
    "normalize_run_budget_limits",
    "resolve_owner_from_binding",
    "resolve_target_skill",
]
