"""Initial schema

Revision ID: a7d8f1424a99
Revises: 
Create Date: 2026-01-08 22:28:31.455508

"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'a7d8f1424a99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('graph_enabled', sa.Boolean(), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_type_code'), 'entry_type', ['code'], unique=True)
    op.create_index(op.f('ix_entry_type_id'), 'entry_type', ['id'], unique=False)
    op.create_table('relation_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('inverse_name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('directed', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relation_type_code'), 'relation_type', ['code'], unique=True)
    op.create_index(op.f('ix_relation_type_id'), 'relation_type', ['id'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_id'), 'tag', ['id'], unique=False)
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.create_table('entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('time_mode', sa.Enum('NONE', 'POINT', 'RANGE', name='timemode'), nullable=False),
    sa.Column('time_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['entry_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_id'), 'entry', ['id'], unique=False)
    op.create_index(op.f('ix_entry_time_at'), 'entry', ['time_at'], unique=False)
    op.create_index(op.f('ix_entry_type_id'), 'entry', ['type_id'], unique=False)
    op.create_table('attachment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_entry_id'), 'attachment', ['entry_id'], unique=False)
    op.create_index(op.f('ix_attachment_id'), 'attachment', ['id'], unique=False)
    op.create_table('entry_tag',
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('entry_id', 'tag_id')
    )
    op.create_table('relation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_entry_id', sa.UUID(), nullable=False),
    sa.Column('target_entry_id', sa.UUID(), nullable=False),
    sa.Column('relation_type_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['relation_type_id'], ['relation_type.id'], ),
    sa.ForeignKeyConstraint(['source_entry_id'], ['entry.id'], ),
    sa.ForeignKeyConstraint(['target_entry_id'], ['entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relation_id'), 'relation', ['id'], unique=False)
    op.create_index(op.f('ix_relation_relation_type_id'), 'relation', ['relation_type_id'], unique=False)
    op.create_index(op.f('ix_relation_source_entry_id'), 'relation', ['source_entry_id'], unique=False)
    op.create_index(op.f('ix_relation_target_entry_id'), 'relation', ['target_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relation_target_entry_id'), table_name='relation')
    op.drop_index(op.f('ix_relation_source_entry_id'), table_name='relation')
    op.drop_index(op.f('ix_relation_relation_type_id'), table_name='relation')
    op.drop_index(op.f('ix_relation_id'), table_name='relation')
    op.drop_table('relation')
    op.drop_table('entry_tag')
    op.drop_index(op.f('ix_attachment_id'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_entry_id'), table_name='attachment')
    op.drop_table('attachment')
    op.drop_index(op.f('ix_entry_type_id'), table_name='entry')
    op.drop_index(op.f('ix_entry_time_at'), table_name='entry')
    op.drop_index(op.f('ix_entry_id'), table_name='entry')
    op.drop_table('entry')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_index(op.f('ix_tag_id'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_relation_type_id'), table_name='relation_type')
    op.drop_index(op.f('ix_relation_type_code'), table_name='relation_type')
    op.drop_table('relation_type')
    op.drop_index(op.f('ix_entry_type_id'), table_name='entry_type')
    op.drop_index(op.f('ix_entry_type_code'), table_name='entry_type')
    op.drop_table('entry_type')
    # ### end Alembic commands ###
