"""Plan 07 durable Workflow/Agent execution contracts package.

Task 1: portable frozen contracts + codec.
Task 2: frozen DurableExecutionPlanV1 planner + durable publish helpers.
Task 3: one-boundary durable Workflow/Agent runner + node adapters.
"""

from __future__ import annotations

from app.assistant.workflow.durable.contracts import (  # noqa: F401
    DURABLE_WORKFLOW_IDENTITY_NAMESPACE,
    BudgetSuspensionStateV1,
    DurableBranchDecisionV1,
    DurableCallFrameV1,
    DurableEdgeV1,
    DurableExecutionPlanV1,
    DurableLoopCursorV1,
    DurableNodePlanV1,
    DurablePauseEffectPort,
    DurablePauseProposalV1,
    DurableWorkflowStateV1,
    FrozenExecutionDependencyRef,
    build_root_continuation,
    compute_branch_decision_digest,
    compute_loop_cursor_digest,
    compute_plan_digest,
    compute_proposal_digest,
    compute_suspension_digest,
    derive_frame_id,
    derive_interrupt_id,
    derive_node_visit_id,
)
from app.assistant.workflow.durable.context import EphemeralWorkflowContext  # noqa: F401
from app.assistant.workflow.durable.planner import (  # noqa: F401
    DURABLE_PLAN_EXTENSION_CONTRACT_VERSION,
    DURABLE_PLAN_EXTENSION_KEY,
    DurablePlanError,
    attach_durable_plan_extension,
    business_side_effect_maximum,
    extract_durable_plan_digest,
    plan_allows_durable_interrupt,
    plan_durable_execution,
    plan_durable_execution_from_surface,
    plan_parallel_safe,
    publish_durable_binding_snapshot,
)
from app.assistant.workflow.durable.adapters import (  # noqa: F401
    AdapterBoundaryResult,
    AdapterExecutionContext,
    DefaultDurableNodeAdapterRegistry,
    DurableAdapterError,
    PortableNodeBag,
    build_default_registry,
)
from app.assistant.workflow.durable.runner import (  # noqa: F401
    BoundaryKind,
    BoundaryResult,
    DurableFrameMaterial,
    DurableWorkflowRunner,
    PreparedBoundary,
    build_initial_workflow_state,
    commit_workflow_boundary_prepare,
    commit_workflow_boundary_result,
)

__all__ = [
    "DURABLE_PLAN_EXTENSION_CONTRACT_VERSION",
    "DURABLE_PLAN_EXTENSION_KEY",
    "DURABLE_WORKFLOW_IDENTITY_NAMESPACE",
    "BudgetSuspensionStateV1",
    "DurableBranchDecisionV1",
    "DurableCallFrameV1",
    "DurableEdgeV1",
    "DurableExecutionPlanV1",
    "DurableLoopCursorV1",
    "DurableNodePlanV1",
    "DurablePauseEffectPort",
    "DurablePauseProposalV1",
    "DurablePlanError",
    "DurableWorkflowStateV1",
    "EphemeralWorkflowContext",
    "FrozenExecutionDependencyRef",
    "attach_durable_plan_extension",
    "build_root_continuation",
    "business_side_effect_maximum",
    "compute_branch_decision_digest",
    "compute_loop_cursor_digest",
    "compute_plan_digest",
    "compute_proposal_digest",
    "compute_suspension_digest",
    "derive_frame_id",
    "derive_interrupt_id",
    "derive_node_visit_id",
    "extract_durable_plan_digest",
    "plan_allows_durable_interrupt",
    "plan_durable_execution",
    "plan_durable_execution_from_surface",
    "plan_parallel_safe",
    "publish_durable_binding_snapshot",
    "AdapterBoundaryResult",
    "AdapterExecutionContext",
    "BoundaryKind",
    "BoundaryResult",
    "DefaultDurableNodeAdapterRegistry",
    "DurableAdapterError",
    "DurableFrameMaterial",
    "DurableWorkflowRunner",
    "PortableNodeBag",
    "PreparedBoundary",
    "build_default_registry",
    "build_initial_workflow_state",
    "commit_workflow_boundary_prepare",
    "commit_workflow_boundary_result",
]
