"""Shared capability runtime contracts package (Plan 02).

Pure frozen contracts, safe errors, runtime ports, and schema compilation.
Does not access the database, Tool Registry, Workflow engine, OpenClaw, or Provider code.
"""

from __future__ import annotations

from app.assistant.capabilities.contracts import (
    MAX_SAFE_MESSAGE_LEN,
    ArtifactRef,
    CapabilityAuthorizationEvidence,
    CapabilityAvailability,
    CapabilityBehavior,
    CapabilityCompletionMetadata,
    CapabilityDescriptor,
    CapabilityEntrypoint,
    CapabilityError,
    CapabilityEventMetadata,
    CapabilityEventType,
    CapabilityExecutionContext,
    CapabilityExecutionRequest,
    CapabilityMetrics,
    CapabilityOwnerRef,
    CapabilityPolicyDecision,
    CapabilityPrincipal,
    CapabilityResult,
    CapabilityRuntimeEvent,
    CapabilityTimeoutPolicy,
    CapabilityValidationIssue,
    ClassificationContractRef,
    ContinuationRef,
    EvidenceIssuer,
    EvidenceVerifierKey,
    FrozenBindingProvenance,
    FrozenCapabilityBinding,
    SideEffectClass,
    VerifiedAuthorizationEvidence,
    cancelled_result,
    completed_result,
    failed_result,
    project_frozen_capability_binding,
)
from app.assistant.capabilities.errors import (
    CapabilityDomainError,
    CapabilitySchemaValidationError,
    sanitize_unexpected_exception,
)
from app.assistant.capabilities.json_schema import (
    CompiledBindingSchema,
    binding_schema_digest,
    compile_binding_schema,
    normalize_binding_schema,
    validate_json_value,
)
from app.assistant.domain.contracts import (
    CapabilityCompletionContract,
    ResolvedCapabilityBinding,
    ResolvedCapabilityDependency,
    ResolvedCapabilityRef,
)

__all__ = [
    "MAX_SAFE_MESSAGE_LEN",
    "ArtifactRef",
    "CapabilityAuthorizationEvidence",
    "CapabilityAvailability",
    "CapabilityBehavior",
    "CapabilityCompletionContract",
    "CapabilityCompletionMetadata",
    "CapabilityDescriptor",
    "CapabilityDomainError",
    "CapabilityEntrypoint",
    "CapabilityError",
    "CapabilityEventMetadata",
    "CapabilityEventType",
    "CapabilityExecutionContext",
    "CapabilityExecutionRequest",
    "CapabilityMetrics",
    "CapabilityOwnerRef",
    "CapabilityPolicyDecision",
    "CapabilityPrincipal",
    "CapabilityResult",
    "CapabilityRuntimeEvent",
    "CapabilitySchemaValidationError",
    "CapabilityTimeoutPolicy",
    "CapabilityValidationIssue",
    "ClassificationContractRef",
    "CompiledBindingSchema",
    "ContinuationRef",
    "EvidenceIssuer",
    "EvidenceVerifierKey",
    "FrozenBindingProvenance",
    "FrozenCapabilityBinding",
    "ResolvedCapabilityBinding",
    "ResolvedCapabilityDependency",
    "ResolvedCapabilityRef",
    "SideEffectClass",
    "VerifiedAuthorizationEvidence",
    "binding_schema_digest",
    "cancelled_result",
    "compile_binding_schema",
    "completed_result",
    "failed_result",
    "normalize_binding_schema",
    "project_frozen_capability_binding",
    "sanitize_unexpected_exception",
    "validate_json_value",
]
